### ISSUE TITLE
[yuzu] Can't launch the game with this mod installed

### ISSUE THREAD

**Issue by Yashirow** [Lincoln-LM/swsh-mods-exl#12]
Hi, got this error while launching the game. I tried launching with the mod installed to :

1. SDMC/Atmosphere (`yuzu\sdmc\atmosphere\contents\01008DB008C2C000`)
2. yuzu mods directory (`yuzu\load\01008DB008C2C000`)
- and the config always in (`yuzu\sdmc\config`)

Also tried to disable every other mods but still got the same result. I think it's because of the `main.npdm` file but why ? I don't know.

![image](https://github.com/user-attachments/assets/0747e632-4ee4-459e-bd11-4b9207b5141e)

<details>
<summary>ROM infos if needed</summary>

![image](https://github.com/user-attachments/assets/f2442d7f-bbfb-4140-a4e4-6c92c69bfdb9)

</details>

Edit : According to [this website](https://yuzu-mirror.github.io/help/feature/game-modding/), any files inside the `exefs` folder should be either an `.ips` file or a `.pchtxt` file

**Comment by Yashirow** [comment]
I switched to Ryujinx and found it works perfectly there. In my opinion, it’s a much better option. If you don’t plan to add compatibility with yuzu, feel free to close this issue!

**Comment by Lincoln-LM** [comment]
> I switched to Ryujinx and found it works perfectly there. In my opinion, it’s a much better option. If you don’t plan to add compatibility with yuzu, feel free to close this issue!

yeah I'm not particularly interesting in debugging why it wouldn't be working on yuzu but the fact that it can work on ryu is useful information. if you're willing to right up the rough steps (where files need to go, if any settings need to be changed, etc.) that's missing for this issue https://github.com/Lincoln-LM/swsh-mods-exl/issues/9

**Comment by MultiKoopa** [comment]
Is there really no way to get this working in Yuzu? Yuzu pretty much always performs significantly better for me because of my older hardware.

EDIT: I think I've got it!
inside \yuzu\load\01008DB008C2C000 (for Pokemon Shield), place the renamed "swsh-mods-exl" folder that includes the "exefs" and "romfs" folders;
inside \yuzu\sdmc\, paste the config folder directly

seems the config folder DOES need to go into the sd root, but the actual mod itself goes into the normal mods location, since I'm not sure Yuzu actually makes use of the "Atmosphere mods" location like Ryujinx does.
