### ISSUE TITLE
[Documentation] Emulator Install Guide

### ISSUE THREAD

**Issue by Lincoln-LM** [Lincoln-LM/swsh-mods-exl#9]
Switch emulators (ryu/yuzu) have their own way of loading mods that may not be compatible with atmosphere's layeredfs layout. I am not familiar with either of these or really interested in figuring it out so this issue stands as a notice that it would be helpful to have done.

**Comment by Yashirow** [comment]
_Click on text with arrows for visual informations_

# [Installation with Ryujinx]

Download the latest release of the mod (SWORD or SHIELD depending of your version) and extract the files
<details>
<summary>Open the folder until you find a folder with the game ID : rename it "swsh-mods-exl"

</summary>

![image](https://github.com/user-attachments/assets/21ff410e-e4af-4885-86fa-ca26666c9d9a)

</details>
<details>
<summary>Right click on the game in Ryujinx library and chose the "Open Atmosphere Mods Directory"</summary>

![image](https://github.com/user-attachments/assets/1b19c2ca-7db9-4879-b6d2-53bae3d2a03b)

</details>
<details>
<summary>Paste the "swsh-mods-exl" folder here</summary>

![image](https://github.com/user-attachments/assets/b7edfb24-3738-4a11-b48c-b30151078cff)

</details>
<details>
<summary>Navigate up three directory levels until you see the "atmosphere" and "Nintendo" folders. Paste the config folder here and that's it</summary>

![image](https://github.com/user-attachments/assets/60885c2c-ec05-437a-9565-c571545011aa)

</details>

# [Installation with yuzu]

Doesn't work for me so idk

**Comment by MultiKoopa** [comment]
I think I've got it working on Yuzu!
inside \yuzu\load\01008DB008C2C000 (for Pokemon Shield), place the renamed "swsh-mods-exl" folder that includes the "exefs" and "romfs" folders;
inside \yuzu\sdmc\, paste the config folder directly

seems the config folder DOES need to go into the sd root, but the actual mod itself goes into the normal mods location, since I'm not sure Yuzu actually makes use of the "Atmosphere mods" location like Ryujinx does.
